### ISSUE TITLE
Drupal core patch fails to apply as changes are made to file in sites/ directory

### ISSUE THREAD

**Issue by snpower** [cweagans/composer-patches#117]
Sorry if this is a known issue, but I couldn't see another issue similar to this.

The patch at https://www.drupal.org/node/2641118#comment-11981316 fails to apply when using composer-patches as composer first changes directory into web/core/ before attempting to apply the patch. Since the patch modifies the default.services.yml file in sites/default/ and since sites/default/ is not within the web/core/ directory (but rather web/), the patch fails to apply.

Stella

**Comment by cweagans** [comment]
This is a known issue. Unfortunately, there's not a lot I can do about it unless there's some way to tell `git apply` to ignore hunks outside of a certain directory. *That* would be amazing.

In the mean time, if you strip out the part of the patch that changes default.services.yml, the patch should apply cleanly. You might consider just uploading that stripped down patch to the issue queue with -do-not-test so that others can benefit as well.

If you happen to find a way to make `git apply` or `patch` ignore stuff outside of a certain directory though, do let me know and I'll spend the time to add support for it. I've run into this a few times but haven't had the time to go hunting through man pages.
