### ISSUE TITLE
Feature request: merge patches-file with defined patches in composer.json

### ISSUE THREAD

**Issue by hostep** [cweagans/composer-patches#139]
Hi!

We maintain a whole bunch of projects based on the same composer package (Magento2, but that doesn't matter).

We have a separate composer package which we maintain ourself, which contains a bunch of patches which we apply on all our projects.

When we install this package into a project, it copies a file `composer.paches.json` into the root directory of the project. And we then include this file in the projects `composer.json` file like this:
```json
    "extra": {
        "patches-file": "composer.patches.json"
    }
```
The `composer.patches.json` file contains something like this:
```json
{
    "patches": {
        "vendor/module": {
            "patch installed in all our projects": "file.patch",
        },
        "vendor/module2": {
            "patch installed in all our projects": "file2.patch",
        }
    }
}

```

This is so that we can apply new patches on a bunch of projects just by running `composer update` (twice, but that's no problem). Instead of having to copy and paste the patches all over our projects with the chance of forgetting something.

This works perfectly fine. It patches the modules in the project after running `composer update`.

But sometimes there is a need for applying one or multiple extra patches on top of those "default" ones for one specific project.

Currently we are unable to do this. It would be nice if we could also specify extra patches for the project specific in the `composer.json` file, something like this:
```json
    "extra": {
        "patches-file": "composer.patches.json",
        "patches": {
            "vendor/module": {
                "extra patch specific to this project": "file3.patch",
            }
        }
    }
```

Currently, in version 1.6.1, this isn't working, only one of both is being used, I think the inline one takes precedence (but I'm not sure, it's been a while since I've tested this).

It would be great if these patches could get merged somehow.
Not sure if this would be a lot of work to get this working? Otherwise it might be a nice feature for version 2.0?

Thanks!

**Comment by cweagans** [comment]
I'd prefer to leave this for 2.0. The good news is that 2.0 _currently_ works like this - it'll gather all patches from all configured sources and merge them all together. 2.0 also provides you the ability to define your own resolvers, so if you're able to write PHP to retrieve a list of patches, you'll be able to plug it into composer-patches and have it work as part of the main plugin.

The reason I mention this is because one of the requirements driving that feature was the ability to do exactly what you're doing: have a central repository of patches that get applied to multiple projects. In this case, you could have your patch resolver reach out to an API or XML feed or something to get a list of patches.

**Comment by hostep** [comment]
Cool, thanks for the info 👍 
I'll close the issue since it will work like this in 2.0.
