### ISSUE TITLE
Add support for relative path local patches

### ISSUE THREAD

**Issue by edurenye** [cweagans/composer-patches#141]
Right now the relative local path does not work (at least for me in Ubuntu 17.04), and it works fine with absolute path.
But the relative path are more useful if you want to keep track of a patch in your project.

**Comment by commi** [comment]
works for me. the base path of the patch was the home of the library (not the project-root using composer from), and the path to composer.patches.json and from there to the patch-files was relative to project-root.

**Comment by edurenye** [comment]
I'm not sure that I got what you meant, but I tried with the base path in the library directory and libraries directory, it did not work for any of them. I got the following error:

> Could not apply patch! Skipping. The error was: The "../../../patches/commerce_local-1.patch" file could not be downloaded: failed to open stream: No such file or directory

**Comment by commi** [comment]
assume those files:

- /composer.json
- /composer-patches.json
- /vendor/patches/patch.patch
- /vendor/vendorname/libraryname/foo/filetopatch.php

`composer-patches.json` references "vendor/patches/patch.patch" (from project-root)
`patches.patch` references "foo/filetopatch.php" since "/vendor/vendorname/libraryname" is the lib-home.

**Comment by edurenye** [comment]
Ok, now it works. Thank you.
I tried this at the beginning and did not work. I though that was because of the path, but probably is one of the random failure I always have, probably related to this issue #145.
So we can close this.
