### ISSUE TITLE
Patch a non composer-managed repository 

### ISSUE THREAD

**Issue by sodacrackers** [cweagans/composer-patches#169]
I'm seeing an "error applying patch" but it works just fine if running `$git apply-patch patches/mycustom.patch` 

composer.json is keyed to a composer project, "acquia/blt", but the patch works on code that's custom installed, not via composer.  

Will the library work on code composer doesn't manage?  Again, works fine via git so hoping I can key off of our composer.json packages.  

The composer.json lines are: 
```
    "extra": {
        "enable-patching": true,
        "patches": {
            "acquia/blt": {
                "Update ZZZ library to include our configurations.": "./patches/blt/zzz-configs.patch"
            }
        },

```

**Comment by cweagans** [comment]
No. This will not work.

Can you elaborate on why Composer can't manage the code you want to patch?

**Comment by sodacrackers** [comment]
We're utilizing a library that's not available as a `composer require ...` installed in the application root. A goal is to update it with customizations (actually, to just include our copies of configuration files). 

cweagans/composer-patches runs currently with our Acquia BLT installation.  

But if composer-patches can't be used to run *any* random patch, that option won't work.  As a separate question, will it be possible to create a patch that creates a symlink in a vendor project folder?

**Comment by cweagans** [comment]
No. Composer has to know about the package in order to patch it. There's no getting around this.

If the library that you're using is available to you via Git (or any of the other VCSes that Composer supports), I would recommend removing the library from where it's at in your project, and then defining a custom composer repository in your composer.json (https://getcomposer.org/doc/05-repositories.md#vcs). This will allow you to `composer require` the library without exposing it to the world, and then subsequently apply patches to it.

If this is not an option, you'll have to manage the patches separately. Perhaps you can fire a bash script on the post-install-cmd event (https://getcomposer.org/doc/articles/scripts.md#command-events).

**Comment by wolffc** [comment]
@sodacrackers i would suggest using an `post-install` script https://getcomposer.org/doc/articles/scripts.md
this basically runs a script after a composer-install happend. this is good for some more setup tasks like coping your configuration files in place.
