### ISSUE TITLE
"composer-exit-on-patch-failure": true does not work

### ISSUE THREAD

**Issue by alexdesignworks** [cweagans/composer-patches#170]
As it has been described in https://github.com/cweagans/composer-patches/pull/158, the `"composer-exit-on-patch-failure": true` in `extra` is not being picked up.

This applies to `1.6` only. Current `master` works correctly. Making a release would resolve this.

**Comment by danepowell** [comment]
This is fixed in 1.x, as mentioned here: https://github.com/cweagans/composer-patches/pull/166

https://github.com/cweagans/composer-patches/commit/d011661f9c52e416ced423dd85979f84f90929ed

There shouldn't be anything left to fix here, and there's nothing stopping you from using 1.x-dev, although tagging a new release on 1.x would make it easier to grab.

I'd suggest closing this issue and voicing your concern in https://github.com/cweagans/composer-patches/issues/173

**Comment by alexdesignworks** [comment]
@danepowell 
Using `dev` version is not a great idea, especially if the project is a boilerplate for other projects. I do not see any reason to not release on each bugfix - that is why we use semantic versioning with a last digit being a patch/fix number.

**Comment by cweagans** [comment]
> I do not see any reason to not release on each bugfix

That's really poor release management. I'm not doing that. The last couple of releases were an exception due to high priority bugs.

Additionally, `master` is probably not what you want to be using anyway. That's eventually going to be 2.x, but it's not ready yet.
