### ISSUE TITLE
can't use patches-ignore on patches defined in root composer.json

### ISSUE THREAD

**Issue by joachim-n** [cweagans/composer-patches#246]
If you use wikimedia/composer-merge-plugin, then the 'merge-plugin' section of composer can specify other JSON files that should be merged into the root composer.json. Composer sees the result of the merge as being the actual content of the composer.json.

This means that you could be in a situation where a file that's merged in adds a patch that you don't want.

This happens with acquia/blt. I had drupal/core 8.5.6 and acquia/blt 9.1.8  acquia/blt requires you to merge some extra JSON files, and these specify a patch to drupal/core 8.5.x. This patch no longer applies to drupal/core 8.6.x, and so to update core, I needed to ignore the patch. That's not possible, as composer-patches sees it as being in the root composer.json.

**Comment by cweagans** [comment]
`main` doesn't resolve patches from dependencies anymore and expects the config in composer.json or in your patches file to be the authoritative source of information. I've made a note to dispatch events pre- and post-patch resolution so that you can modify the patches as you'd like programmatically though.
