### ISSUE TITLE
Track last issue comment, throw warning if new comment posted

### ISSUE THREAD

**Issue by damienmckenna** [cweagans/composer-patches#301]
It would be really useful, in the interest of getting project maintainers to keep up with an issue's progress through the discussion process, if the last comment could be tracked, and when new comments are added to the issue for it to output a warning.

See this discussion for some related points: https://twitter.com/eojthebrave/status/1230931699602722816

**Comment by cweagans** [comment]
I think it would be possible to do this in 2.x, although it might need to be in a plugin that extends this one. My plan is to dispatch events that other plugins can respond to in order to do things like this that don't make sense for the main plugin (Magento users, for example, definitely don't care about the d.o issue queue).

You might even be able to do this now, since 1.x dispatches events before and after applying a patch.

**Comment by cweagans** [comment]
I've made a note to document how to do something like this as part of the 2.0.0 release.
