### ISSUE TITLE
create / rename / delete files

### ISSUE THREAD

**Issue by rvitaliy** [cweagans/composer-patches#333]
It's possible to create / rename / delete files with patch?
if yes, can you link me some documentation please.

Thanks!
Vitaliy

**Comment by cweagans** [comment]
Yep!

Easiest way to do it is to clone whatever project you're working on, make the changes you want to make, `git add` your changes, and then `git diff --cached > your_patch_file.patch`. Then, set up the patch normally in composer.json (see readme for this project) and everything should work. This plugin works best when you have made the patch available somewhere publicly (for instance, you could post a Gist like I did here: https://gist.github.com/cweagans/f7ed4fc642289470671c -- just make sure that when you're telling composer-patches about your patch, you click the "Raw" link so that you get a URL like this: https://gist.githubusercontent.com/cweagans/f7ed4fc642289470671c/raw/0cae9ceaaf1c29fd96df2d85bd10eced6fc1b17f/-). You can also do patches that are only stored in your local repo, but path resolution can sometimes lead to some confusion: specify the path to the local patch relative to the root of the repo that is pulling in your dependency, not relative to the root of the project that you're modifying.
