### ISSUE TITLE
Support alternative transport or proxy

### ISSUE THREAD

**Issue by skyred** [cweagans/composer-patches#408]
When `ALL_PROXY`, `HTTPS_PROXY`, `HTTP_PROXY` are present in the environment, composer can work with them, but patching stops working, below is an example error message:

```
Gathering patches for dependencies. This might take a minute.
  - Installing drupal/commerce_stripe (dev-1.x 66b6b4d): Cloning 66b6b4de23 from cache
  - Applying patches for drupal/commerce_stripe
    https://www.drupal.org/files/issues/2021-10-04/commerce_stripe-allow-off_session-payment-intents-for-recurring-payments-3171408-34.patch (Allow off_session payment intents for recurring payments)
   Could not apply patch! Skipping. The error was: The "https://www.drupal.org/files/issues/2021-10-04/commerce_stripe-allow-off_session-payment-intents-for-recurring-payments-3171408-34.patch" file could not be downloaded: Failed to open stream: Unable to find the socket transport "socks5" - did you forget to enable it when you configured PHP?

                                                                                                                                                                                 
  [Exception]                                                                                                                                                                    
  Cannot apply patch Allow off_session payment intents for recurring payments (https://www.drupal.org/files/issues/2021-10-04/commerce_stripe-allow-off_session-payment-intents  
  -for-recurring-payments-3171408-34.patch)!
  ```
  
Probably, this is caused by http client isn't configured to support proxy (`socks5`), the solution is to find the code, and copy it from composer.

**Comment by noot-to-the-noot** [comment]
I am currently running into a similar problem with a HTTP(S) proxy, I've also tried SOCKS5 but to no avail.

Composer is running fine after the installation inside the [php/8.1-fpm-bullseye](https://hub.docker.com/layers/library/php/8.1-fpm-bullseye/images/sha256-92b09bb98bb9ad33d5ea72942b98924117ac190f51e6257754263be91fd50504) docker container.
This image contains cURL and OpenSSL bundled with PHP so composer can use cURL to connect to the proxy and install everything usually (as it seems so far from my testing).

Now comes this plugin. I've dug trough some of the error messages and some code to come across this line here

https://github.com/cweagans/composer-patches/blob/fac6b311ba47601d575a09b01b859c5544012425/src/Plugin/Patches.php#L317

It creates it's own RemoteFilesystem instance that apparently isn't aware of any proxy usage and thus fails in an error (for me: "You must enable the curl extension to make https requests through a secure proxy.").

I have zero knowledge of PHP but if possible can you use the code used by composer, or get composer to download those resources for you? Otherwise here is the [merge](https://github.com/composer/composer/pull/9324) that added proxy capabilities to composer, it's quite a old so maybe you're better of looking into the current source code [here](https://github.com/composer/composer/tree/main/src/Composer/Util/Http).

Hope to hear back and if I can help in any way just contact me!

**Comment by skyred** [comment]
@noot-to-the-noot Thanks a lot for digging into the details. They are very helpful. I was able to put together a PR to fix the issue.

**Comment by skyred** [comment]
This feature can improve a lot of developers' lives in China and some behind corporate firewall. @danepowell Can you please consider roll a minor release? or merge it to 1.x-dev?

Because most packages who use patches specified `"cweagans/composer-patches": "~1.0"` in their composer.json, there is no easy way to switch a project to use `dev-master` branch right now to use proxies.

**Comment by danepowell** [comment]
I merged it into 1.x. Since there's no automated tests on 1.x, this needs extensive manual testing. Can the folks in this thread please test and confirm this works as expected on 1.x-dev before we cut a new release?

**Comment by cweagans** [comment]
Just to confirm: I have maintained this functionality in #447 as well, so this should continue working in 2.x.

**Comment by cweagans** [comment]
Let us know if this doesn't work for you and we can reopen. Closing for now.

**Comment by skyred** [comment]
> I merged it into 1.x. Since there's no automated tests on 1.x, this needs extensive manual testing. Can the folks in this thread please test and confirm this works as expected on 1.x-dev before we cut a new release?

Yes, I tested it. It is working in 1.x. All I need to do is `composer require cweagans/composer-patches 1.x-dev` . @danepowell Thanks again

**Comment by cweagans** [comment]
@skyred if you can provide some details about how you tested, that would be helpful. I'd be open to tagging a 1.x release so you don't have to use a dev version.

**Comment by skyred** [comment]
For testing, one would need a proxy server. It could be a remote or at your local. Then, you can up those environment variables, so `curl`, `composer` and `composer-patches` would automatically use proxy.

```
ALL_PROXY=socks5://host.docker.internal:9999
HTTP_PROXY=socks5://host.docker.internal:9999
HTTPS_PROXY=socks5://host.docker.internal:9999
```
_Above example is to let docker container use a socks5  proxy on the host machine at port 9999_

With the current stable `composer-patches`,  one would run into errors like what described at the beginning of this issue, after switching to `1.x-dev`, it simply works.
