### ISSUE TITLE
The patch is partially applied

### ISSUE THREAD

**Issue by miroslav-lee** [cweagans/composer-patches#517]
### Verification

- [X] I have updated Composer to the most recent stable release (`composer self-update`)
- [X] I have updated Composer Patches to the most recent stable release (`composer update cweagans/composer-patches`)
- [X] I am using one of the supported PHP versions (8.0+)
- [X] I have searched existing issues _and_ discussions for my problem.
- [X] My problem is _not_ addressed in the [troubleshooting guide](https://docs.cweagans.net/composer-patches/troubleshooting/guide).

### What were you trying to do (and why)?

I try to apply patch

### What happened? What did you expect to happen?

Could not apply patch! Skipping. The error was: Cannot apply patch. 
It's ok.
But I found that part of the patch was applied and part was not. 
Sometimes this provokes errors on the PHP side, since, for example, part of the Namespaces was removed from the USE section (as it should be, according to the patch), and the class that should have been removed remained. That's where the problems come in.

I guess it's because of the `--no-backup-if-mismatch` parameter in the `patch` command what is executing.

Can we remove this parameter? Or add some options to whom it is necessary, he turned off, and to whom it is not necessary - turned on.

### Contents of `composer.json`

```shell
''
```

### Contents of `patches.lock.json`

```shell
''
```

### Full output of `composer patches-doctor`

```shell
''
```

### Full output of relevant Composer command with the `-vvv` flag added

```shell
''
```

**Comment by cweagans** [comment]
No details given.

**Comment by miroslav-lee** [comment]
But what details do you need?
If you mean Contents of composer.json, patches.lock.json etc. then I can't give this information, because policy privacy of company. 

And I'm sure that it's not needed. Just try to apply patch which will be skipped.
Or read documentation of the `patch` utility and `--no-backup-if-mismatch` option.

**Comment by cweagans** [comment]
I'm not going to make a change to this plugin that will affect literally every single user for a scenario that I can't reproduce. I'm not going to try to guess the specific details of your environment, `patch` version/variant, contents of your patch, etc. That's why the template is there. If you can't provide those details, there's not much help I can give you.

Wild guess: your patch probably needs to be rerolled. You can find some info about how to do that here: https://www.drupal.org/docs/develop/git/using-git-to-contribute-to-drupal/working-with-patches/rerolling-patches

**Comment by cweagans** [comment]
@alexn-at-work Your patch needs re-rolled. You should probably also try 2.x.
